'use strict';

/**
 * Implement bullsAndCows function:
 *
 * Function takes 2 strings: generatedNumber (generated by computer) and
 * enteredNumber (entered by player) and returns count of bulls and cows
 * according to rules (see readme.md). Each parameter should be at most 4 digits
 * long.
 *
 * Function returns result as array of numbers where result[0] is a count of
 * bulls and result[1] is a count of cows.
 *
 * If wrong parameter enteredNumber is given function returns undefined.
 *
 * bullsAndCows('1234', '1345') === [1, 2]
 * bullsAndCows('1234', '1234') === [4, 0]
 * bullsAndCows('1234', '') === undefined
 * bullsAndCows('1234', '12') === undefined
 * bullsAndCows('1234', 'asdf') === undefined
 * bullsAndCows('1234', '1234567890') === undefined
 *
 * @param {string} generatedNumber
 * @param {string} enteredNumber
 *
 * @return {number[]}
 */
function bullsAndCows(generatedNumber, enteredNumber) {
  // write code here
}

module.exports = bullsAndCows;
